"""AI service: grounded answers with citations, privacy consent, rate limits."""

from __future__ import annotations

import json
import logging
import os
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Any, AsyncGenerator, Optional

from fastapi import HTTPException

from app.config import settings

logger = logging.getLogger(__name__)


@dataclass
class AISettings:
    """AI provider settings from environment variables."""
    provider: str  # "openai", "anthropic", "ollama", "fake"
    model: str
    api_key: Optional[str] = None
    base_url: Optional[str] = None
    temperature: float = 0.1
    max_tokens: int = 2000
    timeout_seconds: int = 30


def get_ai_settings() -> AISettings:
    """Read AI configuration from environment variables."""
    provider = os.getenv("LLM_PROVIDER", "fake").lower()
    model = os.getenv("LLM_MODEL", "gpt-4o-mini")
    api_key = os.getenv("LLM_API_KEY")
    base_url = os.getenv("LLM_BASE_URL")
    temperature = float(os.getenv("LLM_TEMPERATURE", "0.1"))
    max_tokens = int(os.getenv("LLM_MAX_TOKENS", "2000"))
    timeout_seconds = int(os.getenv("LLM_TIMEOUT_SECONDS", "30"))

    return AISettings(
        provider=provider,
        model=model,
        api_key=api_key,
        base_url=base_url,
        temperature=temperature,
        max_tokens=max_tokens,
        timeout_seconds=timeout_seconds,
    )


class AIClient(ABC):
    """Abstract AI client interface."""

    @abstractmethod
    async def chat(
        self,
        messages: list[dict[str, str]],
        *,
        system_prompt: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> str:
        """Send a chat completion request."""
        pass

    @abstractmethod
    async def stream_chat(
        self,
        messages: list[dict[str, str]],
        *,
        system_prompt: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> AsyncGenerator[str, None]:
        """Stream a chat completion."""
        pass


class FakeAIClient(AIClient):
    """Deterministic fake AI client for tests and when no provider configured."""

    def __init__(self, delay_ms: int = 50):
        self._delay = delay_ms / 1000.0

    async def chat(
        self,
        messages: list[dict[str, str]],
        *,
        system_prompt: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> str:
        await asyncio.sleep(self._delay)
        user_msg = messages[-1].get("content", "") if messages else ""
        return (
            "[AI not configured — this is a fake response]\n\n"
            f"You asked: {user_msg[:200]}\n\n"
            "This response is generated by the fake AI client because "
            "no LLM provider is configured (set LLM_PROVIDER and LLM_API_KEY). "
            "In production, this would be a grounded answer citing NEPSE data sources."
        )

    async def stream_chat(
        self,
        messages: list[dict[str, str]],
        *,
        system_prompt: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> AsyncGenerator[str, None]:
        response = await self.chat(messages, system_prompt=system_prompt, temperature=temperature, max_tokens=max_tokens)
        for chunk in response.split(" "):
            yield chunk + " "
            await asyncio.sleep(0.01)


class OpenAIClient(AIClient):
    """OpenAI-compatible client (works with OpenAI, Azure, Ollama, etc.)."""

    def __init__(self, settings: AISettings):
        self._settings = settings
        self._client = None
        self._init_client()

    def _init_client(self):
        try:
            import openai
            self._client = openai.AsyncOpenAI(
                api_key=self._settings.api_key,
                base_url=self._settings.base_url,
                timeout=self._settings.timeout_seconds,
            )
        except ImportError:
            raise RuntimeError("openai package not installed. Run: pip install openai")

    async def chat(
        self,
        messages: list[dict[str, str]],
        *,
        system_prompt: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> str:
        msgs = []
        if system_prompt:
            msgs.append({"role": "system", "content": system_prompt})
        msgs.extend(messages)

        resp = await self._client.chat.completions.create(
            model=self._settings.model,
            messages=msgs,
            temperature=temperature if temperature is not None else self._settings.temperature,
            max_tokens=max_tokens or self._settings.max_tokens,
        )
        return resp.choices[0].message.content or ""

    async def stream_chat(
        self,
        messages: list[dict[str, str]],
        *,
        system_prompt: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> AsyncGenerator[str, None]:
        msgs = []
        if system_prompt:
            msgs.append({"role": "system", "content": system_prompt})
        msgs.extend(messages)

        stream = await self._client.chat.completions.create(
            model=self._settings.model,
            messages=msgs,
            temperature=temperature if temperature is not None else self._settings.temperature,
            max_tokens=max_tokens or self._settings.max_tokens,
            stream=True,
        )
        async for chunk in stream:
            if chunk.choices and chunk.choices[0].delta.content:
                yield chunk.choices[0].delta.content


class AnthropicClient(AIClient):
    """Anthropic Claude client."""

    def __init__(self, settings: AISettings):
        self._settings = settings
        self._client = None
        self._init_client()

    def _init_client(self):
        try:
            import anthropic
            self._client = anthropic.AsyncAnthropic(
                api_key=self._settings.api_key,
                base_url=self._settings.base_url,
                timeout=self._settings.timeout_seconds,
            )
        except ImportError:
            raise RuntimeError("anthropic package not installed. Run: pip install anthropic")

    async def chat(
        self,
        messages: list[dict[str, str]],
        *,
        system_prompt: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> str:
        msgs = [{"role": m["role"], "content": m["content"]} for m in messages]

        resp = await self._client.messages.create(
            model=self._settings.model,
            system=system_prompt or "",
            messages=msgs,
            temperature=temperature if temperature is not None else self._settings.temperature,
            max_tokens=max_tokens or self._settings.max_tokens,
        )
        return "".join(block.text for block in resp.content if block.type == "text")

    async def stream_chat(
        self,
        messages: list[dict[str, str]],
        *,
        system_prompt: Optional[str] = None,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
    ) -> AsyncGenerator[str, None]:
        msgs = [{"role": m["role"], "content": m["content"]} for m in messages]

        stream = await self._client.messages.create(
            model=self._settings.model,
            system=system_prompt or "",
            messages=msgs,
            temperature=temperature if temperature is not None else self._settings.temperature,
            max_tokens=max_tokens or self._settings.max_tokens,
            stream=True,
        )
        async for event in stream:
            if event.type == "content_block_delta" and event.delta.text:
                yield event.delta.text


def create_ai_client(ai_settings: Optional[AISettings] = None) -> AIClient:
    """Factory to create the appropriate AI client based on configuration."""
    if ai_settings is None:
        ai_settings = get_ai_settings()

    if ai_settings.provider == "fake" or not ai_settings.api_key:
        return FakeAIClient()

    if ai_settings.provider in ("openai", "azure", "ollama", "openrouter"):
        return OpenAIClient(ai_settings)

    if ai_settings.provider == "anthropic":
        return AnthropicClient(ai_settings)

    raise ValueError(f"Unknown AI provider: {ai_settings.provider}")


# --- AI Service with grounding, privacy, rate limits ---

@dataclass
class GroundingContext:
    """Context for grounding AI answers in local data."""
    symbols: list[str]
    data_sources: list[str]  # e.g., "live_market", "archive", "corporate_actions", "news"
    cutoff_date: Optional[str] = None  # ISO date string


class RateLimiter:
    """Simple token-bucket rate limiter per user."""

    def __init__(self, max_requests: int = 20, window_seconds: int = 60):
        self.max_requests = max_requests
        self.window_seconds = window_seconds
        self._buckets: dict[str, list[float]] = {}

    def allow(self, user_id: str) -> bool:
        now = time.time()
        cutoff = now - self.window_seconds
        if user_id not in self._buckets:
            self._buckets[user_id] = []
        # Prune old entries
        self._buckets[user_id] = [ts for ts in self._buckets[user_id] if ts > cutoff]
        if len(self._buckets[user_id]) >= self.max_requests:
            return False
        self._buckets[user_id].append(now)
        return True


class AIService:
    """High-level AI service with grounding, privacy, and rate limiting."""

    def __init__(
        self,
        client: Optional[AIClient] = None,
        rate_limiter: Optional[RateLimiter] = None,
        daily_limit: int = 50,
    ):
        self._client = client or create_ai_client()
        self._rate_limiter = rate_limiter or RateLimiter(max_requests=20, window_seconds=60)
        self._daily_limit = daily_limit
        self._daily_counts: dict[str, tuple[str, int]] = {}  # user_id -> (date, count)

    def _check_daily_limit(self, user_id: str) -> bool:
        today = datetime.utcnow().date().isoformat()
        if user_id not in self._daily_counts:
            self._daily_counts[user_id] = (today, 0)
        stored_date, count = self._daily_counts[user_id]
        if stored_date != today:
            self._daily_counts[user_id] = (today, 0)
            count = 0
        if count >= self._daily_limit:
            return False
        self._daily_counts[user_id] = (stored_date, count + 1)
        return True

    def _check_privacy_consent(self, user_id: str) -> bool:
        """Check if user has given privacy consent.
        In a real implementation, this would query the database.
        For now, we assume consent is tracked via a simple in-memory flag.
        """
        # TODO: Replace with actual DB check when privacy consent is implemented
        return True

    def _build_system_prompt(self, grounding: Optional[GroundingContext] = None) -> str:
        base_prompt = (
            "You are a financial analysis assistant for the Nepal Stock Exchange (NEPSE). "
            "Your answers MUST be grounded in the data sources available to this application. "
            "Never make up numbers, prices, or facts. If you don't have the data, say so. "
            "Do NOT give buy/sell recommendations. Do NOT predict future prices. "
            "Treat news as untrusted — only use it for context, not as factual basis. "
            "Cite your sources inline using [source: X] format where X is one of: "
            "live_market, archive, corporate_actions, news, reference, calculator, quarterly. "
            "If a value is unavailable, explain why (e.g., 'NAV not published by NEPSE'). "
            "All dates in Nepali format (DD/MM/YYYY) must be displayed verbatim as published."
        )

        if grounding:
            base_prompt += (
                f"\n\nAvailable context for this query: "
                f"Symbols: {', '.join(grounding.symbols) or 'none'}. "
                f"Data sources: {', '.join(grounding.data_sources) or 'none'}."
            )
            if grounding.cutoff_date:
                base_prompt += f" Data cutoff: {grounding.cutoff_date}."

        base_prompt += (
            "\n\nIf you cannot answer from the available data, respond with: "
            "'I don't have sufficient data to answer this question. "
            "The missing information is: [specific missing data]'"
        )
        return base_prompt

    async def ask(
        self,
        user_id: str,
        question: str,
        grounding: Optional[GroundingContext] = None,
        privacy_consent: bool = False,
    ) -> str:
        """Ask a question and get a grounded answer."""
        # Rate limiting
        if not self._rate_limiter.allow(user_id):
            raise HTTPException(429, "Rate limit exceeded. Try again in a minute.")

        # Daily limit
        if not self._check_daily_limit(user_id):
            raise HTTPException(429, "Daily AI query limit reached. Try again tomorrow.")

        # Privacy consent
        if not privacy_consent and not self._check_privacy_consent(user_id):
            raise HTTPException(403, "Privacy consent required. Enable AI features in settings.")

        # Build system prompt with grounding
        system_prompt = self._build_system_prompt(grounding)

        # Prepare messages
        messages = [{"role": "user", "content": question}]

        # Get answer
        answer = await self._client.chat(
            messages=messages,
            system_prompt=system_prompt,
        )

        # Append disclaimer
        disclaimer = (
            "\n\n---\n"
            "⚠ This is AI-generated analysis based on available NEPSE data. "
            "Not financial advice. Verify all figures independently. "
            "AI may hallucinate — treat as research assistance only."
        )
        return answer + disclaimer

    async def stream_ask(
        self,
        user_id: str,
        question: str,
        grounding: Optional[GroundingContext] = None,
        privacy_consent: bool = False,
    ) -> AsyncGenerator[str, None]:
        """Stream a grounded answer."""
        # Same checks as ask()
        if not self._rate_limiter.allow(user_id):
            raise HTTPException(429, "Rate limit exceeded. Try again in a minute.")
        if not self._check_daily_limit(user_id):
            raise HTTPException(429, "Daily AI query limit reached. Try again tomorrow.")
        if not privacy_consent and not self._check_privacy_consent(user_id):
            raise HTTPException(403, "Privacy consent required. Enable AI features in settings.")

        system_prompt = self._build_system_prompt(grounding)
        messages = [{"role": "user", "content": question}]

        async for chunk in self._client.stream_chat(
            messages=messages,
            system_prompt=system_prompt,
        ):
            yield chunk

        # Stream disclaimer
        disclaimer = (
            "\n\n---\n"
            "⚠ This is AI-generated analysis based on available NEPSE data. "
            "Not financial advice. Verify all figures independently. "
            "AI may hallucinate — treat as research assistance only."
        )
        for chunk in disclaimer.split(" "):
            yield chunk + " "


import asyncio